/**
 * Verifies that every public export of the package entry point
 * (`src/index.js`) resolves: client classes are constructible, utility
 * values exist, and every named type export compiles.
 */
import { describe, expect, it } from 'vitest';

// ── Value imports from the package entry point ───────────────────────────────

import {
  AccountStatusClient,
  AccessControlClient,
  ActivityFeedClient,
  AdminClient,
  AllowancesClient,
  AssetControlClient,
  assertResult,
  BalanceClient,
  BatchConversionClient,
  BatchHistoryClient,
  BatchNotificationsClient,
  BatchPaymentRemindersClient,
  BatchRewardsClient,
  BatchTokenMintClient,
  BatchTransferClient,
  BatchWalletCreationClient,
  BudgetAllocationClient,
  BudgetClient,
  CategoryAnalyticsClient,
  convert,
  CurrencyConversionClient,
  EscrowClient,
  EscrowV2Client,
  FeeClient,
  GatewayError,
  MAINNET,
  MerchantTaggingClient,
  MultiCurrencyWalletClient,
  NotificationClient,
  PausableClient,
  PenaltyClient,
  RecurringPaymentClient,
  RewardsClient,
  SavingsClient,
  SavingsGoalsClient,
  SharedBudgetsClient,
  SorobanGateway,
  SpendingCategoriesClient,
  SpendingLimitsClient,
  SpendingPolicyClient,
  SpendingRulesClient,
  TESTNET,
  TransactionAnalyticsClient,
  TransactionValidationClient,
  TransactionalClient,
  TransactionsClient,
  TransferClient,
  TreasuryClient,
  UserClient,
  UsersClient,
  WalletStatusClient,
  ZkVerifierClient,
} from '../src/index.js';

// ── Type imports from the package entry point ────────────────────────────────

import type {
  // core
  GatewayOptions,
  SubmitOptions,
  SubmitResult,
  TransactionSigner,
  // types.js
  AccountStatusRecord,
  BatchConversionResult,
  BatchFeeResult,
  ConversionRate,
  ConversionRequestInput,
  ConversionResultItem,
  FeeConfig,
  ReconciliationResult,
  WalletConversionRequest,
  WalletConversionResult,
  // batch-transfer
  BatchBurnResult,
  BatchTransferResult,
  BurnRequestInput,
  BurnResultItem,
  TransferRequestInput,
  TransferResultItem,
  // transactions
  TransactionInput,
  TransactionRecord,
  TransactionStatus,
  // recurring-payment
  IncomeStream,
  RecurringPayment,
  // escrow v1 & v2
  BatchReleaseResult,
  BatchReversalResult,
  EscrowRecord,
  EscrowReleaseRequest,
  EscrowReversalRequest,
  EscrowV2Record,
  ReleaseResultItem,
  ReversalResultItem,
  // savings-goals
  AutoAllocationRequestInput,
  AutoAllocationResult,
  BatchGoalResult,
  BatchMilestoneResult,
  ContributionRecord,
  GoalCertificateRecord,
  GoalResultItem,
  MilestoneAchievementRecord,
  MilestoneAchievementRequestInput,
  MilestoneResultItem,
  SavingsGoalProgressRecord,
  SavingsGoalRecord,
  SavingsGoalRequestInput,
  // budget
  BeneficiaryInput,
  BeneficiaryRecord,
  BudgetConfigVersionRecord,
  BudgetFreezeRecord,
  BudgetRecord,
  BudgetRuleInput,
  CategoryBudgetRecord,
  CategoryTransferRecord,
  DelegationPermissionRecord,
  PendingDeletionRecord,
  UserBudgetRecord,
  // shared-budgets
  ArchivedBudgetRecord,
  BudgetContributionRecord,
  BudgetSpendingRuleInput,
  BudgetUtilizationBand,
  BudgetUtilizationSummaryRecord,
  SharedBudgetRecord,
  // budget-allocation
  BatchBudgetResult,
  BudgetAllocationSummaryRecord,
  BudgetRenewalConfigRecord,
  BudgetRequestInput,
  BudgetVersionRecord,
  CategoryBudgetRequestInput,
  UserBudgetCategoriesRecord,
  // spending-limits
  BatchLimitResult,
  EscalationConfigRecord,
  ExceptionRuleRecord,
  LimitUpdateResultItem,
  SpendingLimitRecord,
  SpendingLimitRequestInput,
  // spending-policy
  ApprovalOutcome,
  PendingTransactionRecord,
  PolicyEvaluation,
  PolicyRecord,
  PolicyRuleInput,
  // spending-rules
  EvaluationResultRecord,
  RuleDecision,
  RuleRecord,
  // spending-categories
  SpendingCategoryRecord,
  // batch-rewards
  BatchRewardResult,
  RewardRequestInput,
  RewardResultItem,
  // batch-token-mint
  BatchMintResult,
  MintResultItem,
  TokenMintedRecord,
  TokenMintRequestInput,
  // batch-payment-reminders
  BatchReminderResult,
  PaymentReminderRequestInput,
  // batch-notifications
  BatchNotificationResult,
  NotificationPayloadInput,
  // batch-history
  HistoryTransactionRecord,
  UserHistoryRecord,
  // batch-wallet-creation
  BatchCreateResult,
  BatchRecoveryResult,
  WalletCreateRequestInput,
  WalletCreateResultItem,
  WalletRecord,
  WalletRecoveryRequestInput,
  WalletRecoveryResultItem,
  // treasury
  ProposalRecord,
  ProposalStatus,
  SpendingTierInput,
  SpendingTierRecord,
  // allowances
  AllowanceAnalyticsRecord,
  AllowanceFrequency,
  AllowanceRecord,
  PaymentRecord,
  // rewards
  RewardAccountRecord,
  RewardStatus,
  RewardTransactionRecord,
  RewardType,
  // notification
  DigestSummaryRecord,
  NotificationInput,
  NotificationResultRecord,
  // activity-feed
  ActivityEventRecord,
  // access-control
  Role,
  // wallet-status
  WalletStatus,
  // transactional
  TransactionalTransactionInput,
  TransactionalTransactionRecord,
  // currency-conversion
  ConversionRateInput,
  ConversionRateRecord,
  // merchant-tagging
  MerchantAnalyticsRecord,
  MerchantRecord,
  TransactionMerchantTagRecord,
  // category-analytics
  CategoryAnalyticsEventInput,
  CategorySpendInput,
  CategorySpendingRecord,
  MonthlyAnalyticsRecord,
  TimeFilterInput,
  // transaction-analytics
  AnalyticsEventInput,
  AnalyticsMonthlyAnalyticsRecord,
  AnalyticsTransactionInput,
  AnalyticsTransactionStatus,
  AuditLogInput,
  BatchMetricsRecord,
  BatchStatusUpdateResultRecord,
  BundleResultRecord,
  BundledTransactionInput,
  CategorySpendWindowRecord,
  FeeCalculationResultRecord,
  FeeConfigInput,
  FeeModelInput,
  FeeTierInput,
  PaginatedBatchMetricsRecord,
  RatingInput,
  RatingResultRecord,
  RefundBatchMetricsRecord,
  RefundRequestInput,
  TransactionStatusUpdateInput,
  UserSpendingSummaryRecord,
} from '../src/index.js';

// Referencing every imported type in a single tuple marks them "used" under
// `noUnusedLocals` while proving each name resolves from the entry point.
type ExportsResolve = [
  GatewayOptions,
  SubmitOptions,
  SubmitResult,
  TransactionSigner,
  AccountStatusRecord,
  BatchConversionResult,
  BatchFeeResult,
  ConversionRate,
  ConversionRequestInput,
  ConversionResultItem,
  FeeConfig,
  ReconciliationResult,
  WalletConversionRequest,
  WalletConversionResult,
  BatchBurnResult,
  BatchTransferResult,
  BurnRequestInput,
  BurnResultItem,
  TransferRequestInput,
  TransferResultItem,
  TransactionInput,
  TransactionRecord,
  TransactionStatus,
  IncomeStream,
  RecurringPayment,
  BatchReleaseResult,
  BatchReversalResult,
  EscrowRecord,
  EscrowReleaseRequest,
  EscrowReversalRequest,
  EscrowV2Record,
  ReleaseResultItem,
  ReversalResultItem,
  AutoAllocationRequestInput,
  AutoAllocationResult,
  BatchGoalResult,
  BatchMilestoneResult,
  ContributionRecord,
  GoalCertificateRecord,
  GoalResultItem,
  MilestoneAchievementRecord,
  MilestoneAchievementRequestInput,
  MilestoneResultItem,
  SavingsGoalProgressRecord,
  SavingsGoalRecord,
  SavingsGoalRequestInput,
  BeneficiaryInput,
  BeneficiaryRecord,
  BudgetConfigVersionRecord,
  BudgetFreezeRecord,
  BudgetRecord,
  BudgetRuleInput,
  CategoryBudgetRecord,
  CategoryTransferRecord,
  DelegationPermissionRecord,
  PendingDeletionRecord,
  UserBudgetRecord,
  ArchivedBudgetRecord,
  BudgetContributionRecord,
  BudgetSpendingRuleInput,
  BudgetUtilizationBand,
  BudgetUtilizationSummaryRecord,
  SharedBudgetRecord,
  BatchBudgetResult,
  BudgetAllocationSummaryRecord,
  BudgetRenewalConfigRecord,
  BudgetRequestInput,
  BudgetVersionRecord,
  CategoryBudgetRequestInput,
  UserBudgetCategoriesRecord,
  BatchLimitResult,
  EscalationConfigRecord,
  ExceptionRuleRecord,
  LimitUpdateResultItem,
  SpendingLimitRecord,
  SpendingLimitRequestInput,
  ApprovalOutcome,
  PendingTransactionRecord,
  PolicyEvaluation,
  PolicyRecord,
  PolicyRuleInput,
  EvaluationResultRecord,
  RuleDecision,
  RuleRecord,
  SpendingCategoryRecord,
  BatchRewardResult,
  RewardRequestInput,
  RewardResultItem,
  BatchMintResult,
  MintResultItem,
  TokenMintedRecord,
  TokenMintRequestInput,
  BatchReminderResult,
  PaymentReminderRequestInput,
  BatchNotificationResult,
  NotificationPayloadInput,
  HistoryTransactionRecord,
  UserHistoryRecord,
  BatchCreateResult,
  BatchRecoveryResult,
  WalletCreateRequestInput,
  WalletCreateResultItem,
  WalletRecord,
  WalletRecoveryRequestInput,
  WalletRecoveryResultItem,
  ProposalRecord,
  ProposalStatus,
  SpendingTierInput,
  SpendingTierRecord,
  AllowanceAnalyticsRecord,
  AllowanceFrequency,
  AllowanceRecord,
  PaymentRecord,
  RewardAccountRecord,
  RewardStatus,
  RewardTransactionRecord,
  RewardType,
  DigestSummaryRecord,
  NotificationInput,
  NotificationResultRecord,
  ActivityEventRecord,
  Role,
  WalletStatus,
  TransactionalTransactionInput,
  TransactionalTransactionRecord,
  ConversionRateInput,
  ConversionRateRecord,
  MerchantAnalyticsRecord,
  MerchantRecord,
  TransactionMerchantTagRecord,
  CategoryAnalyticsEventInput,
  CategorySpendInput,
  CategorySpendingRecord,
  MonthlyAnalyticsRecord,
  TimeFilterInput,
  AnalyticsEventInput,
  AnalyticsMonthlyAnalyticsRecord,
  AnalyticsTransactionInput,
  AnalyticsTransactionStatus,
  AuditLogInput,
  BatchMetricsRecord,
  BatchStatusUpdateResultRecord,
  BundleResultRecord,
  BundledTransactionInput,
  CategorySpendWindowRecord,
  FeeCalculationResultRecord,
  FeeConfigInput,
  FeeModelInput,
  FeeTierInput,
  PaginatedBatchMetricsRecord,
  RatingInput,
  RatingResultRecord,
  RefundBatchMetricsRecord,
  RefundRequestInput,
  TransactionStatusUpdateInput,
  UserSpendingSummaryRecord,
];

/** Every client class exported from the entry point. */
const ALL_CLIENTS = [
  AccountStatusClient,
  AccessControlClient,
  ActivityFeedClient,
  AdminClient,
  AllowancesClient,
  AssetControlClient,
  BalanceClient,
  BatchConversionClient,
  BatchHistoryClient,
  BatchNotificationsClient,
  BatchPaymentRemindersClient,
  BatchRewardsClient,
  BatchTokenMintClient,
  BatchTransferClient,
  BatchWalletCreationClient,
  BudgetAllocationClient,
  BudgetClient,
  CategoryAnalyticsClient,
  CurrencyConversionClient,
  EscrowClient,
  EscrowV2Client,
  FeeClient,
  MerchantTaggingClient,
  MultiCurrencyWalletClient,
  NotificationClient,
  PausableClient,
  PenaltyClient,
  RecurringPaymentClient,
  RewardsClient,
  SavingsClient,
  SavingsGoalsClient,
  SharedBudgetsClient,
  SpendingCategoriesClient,
  SpendingLimitsClient,
  SpendingPolicyClient,
  SpendingRulesClient,
  TransactionAnalyticsClient,
  TransactionValidationClient,
  TransactionalClient,
  TransactionsClient,
  TransferClient,
  TreasuryClient,
  UserClient,
  UsersClient,
  WalletStatusClient,
  ZkVerifierClient,
] as const;

describe('package entry point exports', () => {
  it('exports every contract client class (46 total)', () => {
    expect(ALL_CLIENTS).toHaveLength(46);
    for (const client of ALL_CLIENTS) {
      expect(typeof client).toBe('function');
    }
  });

  it('constructs every client with (gateway, contractId)', () => {
    const gateway = new SorobanGateway({
      rpcUrl: 'https://rpc.invalid',
      networkPassphrase: 'Test SDF Network ; September 2015',
      publicKey: 'GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF',
    });
    for (const client of ALL_CLIENTS) {
      const instance = new client(gateway, 'CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSC4');
      expect(instance).toBeInstanceOf(client);
    }
  });

  it('exports the core gateway utilities', () => {
    expect(typeof SorobanGateway).toBe('function');
    expect(typeof GatewayError).toBe('function');
    expect(typeof assertResult).toBe('function');
    expect(MAINNET.rpcUrl).toMatch(/^https:/);
    expect(MAINNET.networkPassphrase).toContain('Public Global');
    expect(TESTNET.rpcUrl).toMatch(/^https:/);
    expect(TESTNET.networkPassphrase).toContain('Test SDF');
  });

  it('exports the convert helper module with its encoders/decoders', () => {
    for (const fn of [
      'i128',
      'u32',
      'u64',
      'bool',
      'string',
      'address',
      'bytes',
      'bytesN',
      'symbol',
      'vec',
      'struct',
      'voidScVal',
      'decode',
      'returnValueFromMeta',
      'asI128',
      'decodeEnum',
      'decodeEnumItem',
      'decodeEnumVec',
    ]) {
      expect(typeof (convert as Record<string, unknown>)[fn]).toBe('function');
    }
  });

  it('resolves every named type export', () => {
    // Compile-time check: `ExportsResolve` only compiles because every type
    // name imported above exists in the entry point. If any name is missing
    // or misspelled, `tsc` fails before this test ever runs.
    const resolvable: ExportsResolve = [] as unknown as ExportsResolve;
    expect(Array.isArray(resolvable)).toBe(true);
  });
});
