//! # Overdraft Tests
//!
//! Comprehensive tests for the overdraft protection contract including:
//! - Category limit checks before execution
//! - Blocking overdraft attempts
//! - Emitting overdraft attempt events
//! - Negative tests for edge cases

#![cfg(test)]

mod mock {
    use soroban_sdk::testutils::Address as _;
    use soroban_sdk::Symbol;
    use soroban_sdk::{address::Address, map::Map, vec::Vec, Env};

    // Mock token contract for testing
    pub fn create_mock_token(env: &Env) -> Address {
        Address::generate(env)
    }
}

use soroban_sdk::symbol_short;
use soroban_sdk::testutils::Address as _;
use soroban_sdk::{address::Address, map::Map, vec::Vec, Env};

// Import the contract - this will be generated by Soroban
// For testing purposes, we'll define a mock client structure

/// Test helper to create a test environment with contract
fn setup_test_env() -> (Env, Address, Address) {
    let env = Env::default();
    env.ledger().set_timestamp(1000);

    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    client.initialize(&admin);

    (env, contract_id, admin)
}

#[test]
fn test_initialize() {
    let env = Env::default();
    env.ledger().set_timestamp(1000);

    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    client.initialize(&admin);

    assert_eq!(client.get_admin(), admin);
    assert_eq!(client.get_total_overdraft_attempts(), 0);
}

#[test]
#[should_panic(expected = "Already initialized")]
fn test_double_initialize() {
    let env = Env::default();
    env.ledger().set_timestamp(1000);

    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    client.initialize(&admin);

    // Try to initialize again - should panic
    client.initialize(&admin);
}

#[test]
fn test_set_single_category_budget() {
    let env = Env::default();
    env.ledger().set_timestamp(1000);

    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    client.initialize(&admin);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    client.set_category_budget(&admin, &user, &category, &1000i128);

    let category_budget = client.get_category_budget(&user, &category);
    assert!(category_budget.is_some());
    assert_eq!(category_budget.unwrap().limit, 1000);
}

#[test]
fn test_set_multiple_categories() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);

    // Set multiple categories
    client.set_category_budget(&admin, &user, &symbol_short!("food"), &500i128);
    client.set_category_budget(&admin, &user, &symbol_short!("transport"), &300i128);
    client.set_category_budget(&admin, &user, &symbol_short!("entertainment"), &200i128);

    // Verify each category
    assert_eq!(
        client
            .get_category_budget(&user, &symbol_short!("food"))
            .unwrap()
            .limit,
        500
    );
    assert_eq!(
        client
            .get_category_budget(&user, &symbol_short!("transport"))
            .unwrap()
            .limit,
        300
    );
    assert_eq!(
        client
            .get_category_budget(&user, &symbol_short!("entertainment"))
            .unwrap()
            .limit,
        200
    );
}

#[test]
fn test_successful_transaction_within_limit() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Set budget limit of 500
    client.set_category_budget(&admin, &user, &category, &500i128);

    // Spend 200 (should succeed)
    let result = client.validate_transaction(&user, &category, &200i128);
    assert!(result);

    // Check remaining budget is 300
    let check = client.check_transaction(&user, &category, &100i128);
    assert!(check.allowed);
    assert_eq!(check.remaining, 300);
}

#[test]
fn test_exact_limit_transaction() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Set budget limit of 500
    client.set_category_budget(&admin, &user, &category, &500i128);

    // Spend exactly 500 (should succeed)
    let result = client.validate_transaction(&user, &category, &500i128);
    assert!(result);

    // Check remaining budget is 0
    let check = client.check_transaction(&user, &category, &1i128);
    assert!(!check.allowed);
    assert_eq!(check.remaining, 0);
}

#[test]
#[should_panic(expected = "OverdraftLimitExceeded")]
fn test_overdraft_blocked_exceeds_limit() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Set budget limit of 100
    client.set_category_budget(&admin, &user, &category, &100i128);

    // Try to spend 150 (should fail - exceeds limit)
    client.validate_transaction(&user, &category, &150i128);
}

#[test]
fn test_multiple_transactions_accumulate_spending() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Set budget limit of 500
    client.set_category_budget(&admin, &user, &category, &500i128);

    // First transaction: 200
    client.validate_transaction(&user, &category, &200i128);

    // Check remaining: 300
    let check1 = client.check_transaction(&user, &category, &100i128);
    assert_eq!(check1.remaining, 300);

    // Second transaction: 150
    client.validate_transaction(&user, &category, &150i128);

    // Check remaining: 150
    let check2 = client.check_transaction(&user, &category, &100i128);
    assert_eq!(check2.remaining, 150);

    // Third transaction: 200 (should fail - only 150 left)
    let check3 = client.check_transaction(&user, &category, &200i128);
    assert!(!check3.allowed);
    assert_eq!(check3.exceeded_by, 50);
}

// ==================== NEGATIVE TESTS ====================

#[test]
#[should_panic(expected = "OverdraftLimitExceeded")]
fn test_negative_overdraft_after_partial_spending() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Set budget limit of 300
    client.set_category_budget(&admin, &user, &category, &300i128);

    // Spend 250
    client.validate_transaction(&user, &category, &250i128);

    // Try to spend 100 more (should fail - only 50 remaining)
    client.validate_transaction(&user, &category, &100i128);
}

#[test]
#[should_panic(expected = "InvalidAmount")]
fn test_negative_transaction_amount() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    client.set_category_budget(&admin, &user, &category, &1000i128);

    // Try to spend 0 (should fail)
    client.validate_transaction(&user, &category, &0i128);
}

#[test]
#[should_panic(expected = "InvalidAmount")]
fn test_negative_transaction_amount_check() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    client.set_category_budget(&admin, &user, &category, &1000i128);

    // Check with negative amount
    let check = client.check_transaction(&user, &category, &-100i128);
    assert!(!check.allowed);
}

#[test]
#[should_panic(expected = "BudgetNotFound")]
fn test_transaction_without_budget() {
    let (env, _, _) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Try to validate without setting budget first
    client.validate_transaction(&user, &category, &100i128);
}

#[test]
#[should_panic(expected = "CategoryNotFound")]
fn test_check_nonexistent_category() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);

    // Set a budget for food category
    client.set_category_budget(&admin, &user, &symbol_short!("food"), &1000i128);

    // Try to check a different category that doesn't exist
    client.check_transaction(&user, &symbol_short!("transport"), &100i128);
}

#[test]
#[should_panic(expected = "InvalidAmount")]
fn test_set_negative_budget_limit() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Try to set negative budget limit
    client.set_category_budget(&admin, &user, &category, &-100i128);
}

#[test]
#[should_panic(expected = "Unauthorized")]
fn test_unauthorized_admin() {
    let env = Env::default();
    env.ledger().set_timestamp(1000);

    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    let unauthorized = Address::generate(&env);
    client.initialize(&admin);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Try to set budget with wrong admin
    client.set_category_budget(&unauthorized, &user, &category, &1000i128);
}

#[test]
#[should_panic(expected = "OverdraftLimitExceeded")]
fn test_overdraft_at_boundary() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Set budget limit of 1
    client.set_category_budget(&admin, &user, &category, &1i128);

    // Try to spend 2 (should fail)
    client.validate_transaction(&user, &category, &2i128);
}

#[test]
fn test_overdraft_attempts_counter() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Set budget limit of 100
    client.set_category_budget(&admin, &user, &category, &100i128);

    // Initial overdraft attempts should be 0
    assert_eq!(client.get_total_overdraft_attempts(), 0);

    // First overdraft attempt
    let _ = env.try_invoke_contract::<OverdraftContractClient>(
        &contract_id,
        "validate_transaction",
        (&user, &category, &150i128),
    );

    // Should have 1 overdraft attempt
    assert_eq!(client.get_total_overdraft_attempts(), 1);

    // Second overdraft attempt
    let _ = env.try_invoke_contract::<OverdraftContractClient>(
        &contract_id,
        "validate_transaction",
        (&user, &category, &200i128),
    );

    // Should have 2 overdraft attempts
    assert_eq!(client.get_total_overdraft_attempts(), 2);
}

#[test]
fn test_reset_spending() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    client.set_category_budget(&admin, &user, &category, &1000i128);

    // Spend 500
    client.validate_transaction(&user, &category, &500i128);

    // Verify spent is 500
    let cat_budget = client.get_category_budget(&user, &category).unwrap();
    assert_eq!(cat_budget.spent, 500);

    // Reset spending
    client.reset_spending(&admin, &user);

    // Verify spent is 0 but limit remains
    let cat_budget_after = client.get_category_budget(&user, &category).unwrap();
    assert_eq!(cat_budget_after.spent, 0);
    assert_eq!(cat_budget_after.limit, 1000);
}

#[test]
fn test_record_spending() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    client.set_category_budget(&admin, &user, &category, &1000i128);

    // Record spending via admin (not user auth)
    client.record_spending(&admin, &user, &category, &300i128);

    // Verify spent is recorded
    let cat_budget = client.get_category_budget(&user, &category).unwrap();
    assert_eq!(cat_budget.spent, 300);

    // Check remaining budget
    let check = client.check_transaction(&user, &category, &500i128);
    assert!(check.allowed);
    assert_eq!(check.remaining, 700);
}

#[test]
fn test_get_user_budget() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);

    // Set multiple categories
    client.set_category_budget(&admin, &user, &symbol_short!("food"), &500i128);
    client.set_category_budget(&admin, &user, &symbol_short!("transport"), &300i128);

    // Get full user budget
    let user_budget = client.get_user_budget(&user);
    assert!(user_budget.is_some());

    let budget = user_budget.unwrap();
    assert_eq!(budget.user, user);
    assert_eq!(budget.categories.len(), 2);
}

#[test]
fn test_check_transaction_without_spending() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    client.set_category_budget(&admin, &user, &category, &1000i128);

    // Check transaction without spending
    let check = client.check_transaction(&user, &category, &500i128);
    assert!(check.allowed);
    assert_eq!(check.remaining, 1000);
    assert_eq!(check.exceeded_by, 0);

    // Verify spending is still 0
    let cat_budget = client.get_category_budget(&user, &category).unwrap();
    assert_eq!(cat_budget.spent, 0);
}

#[test]
fn test_different_categories_independent() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);

    // Set different limits for different categories
    client.set_category_budget(&admin, &user, &symbol_short!("food"), &500i128);
    client.set_category_budget(&admin, &user, &symbol_short!("transport"), &200i128);
    client.set_category_budget(&admin, &user, &symbol_short!("entertainment"), &100i128);

    // Spend from food
    client.validate_transaction(&user, &symbol_short!("food"), &400i128);

    // Spend from transport
    client.validate_transaction(&user, &symbol_short!("transport"), &150i128);

    // Verify each category tracks spending independently
    assert_eq!(
        client
            .get_category_budget(&user, &symbol_short!("food"))
            .unwrap()
            .spent,
        400
    );
    assert_eq!(
        client
            .get_category_budget(&user, &symbol_short!("transport"))
            .unwrap()
            .spent,
        150
    );
    assert_eq!(
        client
            .get_category_budget(&user, &symbol_short!("entertainment"))
            .unwrap()
            .spent,
        0
    );

    // Check remaining in each
    assert_eq!(
        client
            .check_transaction(&user, &symbol_short!("food"), &200i128)
            .remaining,
        100
    );
    assert_eq!(
        client
            .check_transaction(&user, &symbol_short!("transport"), &100i128)
            .remaining,
        50
    );
    assert_eq!(
        client
            .check_transaction(&user, &symbol_short!("entertainment"), &100i128)
            .remaining,
        100
    );
}

#[test]
#[should_panic(expected = "InvalidAmount")]
fn test_record_spending_negative_amount() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    client.set_category_budget(&admin, &user, &category, &1000i128);

    // Try to record negative spending
    client.record_spending(&admin, &user, &category, &-100i128);
}

#[test]
fn test_overdraft_event_emitted_check() {
    let env = Env::default();
    env.ledger().set_timestamp(1000);

    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    client.initialize(&admin);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    client.set_category_budget(&admin, &user, &category, &100i128);

    // Clear events
    let _ = env.events().all();

    // Trigger overdraft attempt
    let _ = env.try_invoke_contract::<OverdraftContractClient>(
        &contract_id,
        "validate_transaction",
        (&user, &category, &150i128),
    );

    // Check events were emitted
    let events = env.events().all();
    assert!(events.len() > 0);

    // Verify overdraft event was published
    let overdraft_events: Vec<_> = events
        .iter()
        .filter(|e| {
            if let Some(topics) = e.topic().as_vec() {
                topics.len() >= 2 && topics.get(0).unwrap() == symbol_short!("overdraft")
            } else {
                false
            }
        })
        .collect();

    assert!(overdraft_events.len() > 0);
}

#[test]
fn test_zero_budget_limit() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Set budget limit of 0
    client.set_category_budget(&admin, &user, &category, &0i128);

    // Any positive transaction should fail
    let check = client.check_transaction(&user, &category, &1i128);
    assert!(!check.allowed);
    assert_eq!(check.exceeded_by, 1);
}

#[test]
fn test_max_integer_limits() {
    let (env, _, admin) = setup_test_env();
    let contract_id = env.register(OverdraftContract, ());
    let client = OverdraftContractClient::new(&env, &contract_id);

    let user = Address::generate(&env);
    let category = symbol_short!("food");

    // Set very large budget
    let max_budget = i128::MAX / 2;
    client.set_category_budget(&admin, &user, &category, &max_budget);

    // Should handle large amounts
    let check = client.check_transaction(&user, &category, &max_budget);
    assert!(check.allowed);
    assert_eq!(check.remaining, max_budget);
}
