[package]
name = "savings-goals"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk.workspace = true
penalty = { path = "../penalty" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
penalty = { path = "../penalty" }

